---
- hosts: web
  remote_user: root
  gather_facts: no
  tasks:
#    - name: rm /root/.ssh folders
#      file:
#        path: /root/.ssh
#        state: absent

    - name: check /root/.ssh/id_rsa exists
      shell: ls /root/.ssh/id_rsa
      ignore_errors: True
      register: result

    - name: make /root/.ssh/id_rsa
      shell: rm -rf /root/.ssh && ssh-keygen -t rsa -N '' -f /root/.ssh/id_rsa -q
      when: result|failed

    - name: deliver id_rsa.pub
      authorized_key:
        user: root
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        state: present
        exclusive: no